// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "capi_kpack_watcher/model"

	mock "github.com/stretchr/testify/mock"
)

// BuildUpdater is an autogenerated mock type for the BuildUpdater type
type BuildUpdater struct {
	mock.Mock
}

// UpdateBuild provides a mock function with given fields: guid, _a1
func (_m *BuildUpdater) UpdateBuild(guid string, _a1 model.BuildStatus) error {
	ret := _m.Called(guid, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, model.BuildStatus) error); ok {
		r0 = rf(guid, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
