// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/capi-k8s-release/src/registry-buddy/handlers"
	"github.com/google/go-containerregistry/pkg/name"
	"github.com/google/go-containerregistry/pkg/v1/remote"
)

type ImageDescriptorFunc struct {
	Stub        func(name.Reference, ...remote.Option) (*remote.Descriptor, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 name.Reference
		arg2 []remote.Option
	}
	returns struct {
		result1 *remote.Descriptor
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 *remote.Descriptor
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ImageDescriptorFunc) Spy(arg1 name.Reference, arg2 ...remote.Option) (*remote.Descriptor, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 name.Reference
		arg2 []remote.Option
	}{arg1, arg2})
	fake.recordInvocation("ImageDescriptorFunc", []interface{}{arg1, arg2})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.returns.result1, fake.returns.result2
}

func (fake *ImageDescriptorFunc) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *ImageDescriptorFunc) Calls(stub func(name.Reference, ...remote.Option) (*remote.Descriptor, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *ImageDescriptorFunc) ArgsForCall(i int) (name.Reference, []remote.Option) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2
}

func (fake *ImageDescriptorFunc) Returns(result1 *remote.Descriptor, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 *remote.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *ImageDescriptorFunc) ReturnsOnCall(i int, result1 *remote.Descriptor, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 *remote.Descriptor
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 *remote.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *ImageDescriptorFunc) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ImageDescriptorFunc) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handlers.ImageDescriptorFunc = new(ImageDescriptorFunc).Spy
