// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"code.cloudfoundry.org/capi-k8s-release/src/registry-buddy/handlers"
	"code.cloudfoundry.org/capi-k8s-release/src/registry-buddy/package_upload"
	"github.com/google/go-containerregistry/pkg/authn"
)

type UploaderFunc struct {
	Stub        func(string, string, authn.Authenticator) (package_upload.Hash, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 string
		arg2 string
		arg3 authn.Authenticator
	}
	returns struct {
		result1 package_upload.Hash
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 package_upload.Hash
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *UploaderFunc) Spy(arg1 string, arg2 string, arg3 authn.Authenticator) (package_upload.Hash, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 string
		arg2 string
		arg3 authn.Authenticator
	}{arg1, arg2, arg3})
	fake.recordInvocation("UploaderFunc", []interface{}{arg1, arg2, arg3})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.returns.result1, fake.returns.result2
}

func (fake *UploaderFunc) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *UploaderFunc) Calls(stub func(string, string, authn.Authenticator) (package_upload.Hash, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *UploaderFunc) ArgsForCall(i int) (string, string, authn.Authenticator) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2, fake.argsForCall[i].arg3
}

func (fake *UploaderFunc) Returns(result1 package_upload.Hash, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 package_upload.Hash
		result2 error
	}{result1, result2}
}

func (fake *UploaderFunc) ReturnsOnCall(i int, result1 package_upload.Hash, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 package_upload.Hash
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 package_upload.Hash
		result2 error
	}{result1, result2}
}

func (fake *UploaderFunc) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *UploaderFunc) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ handlers.UploaderFunc = new(UploaderFunc).Spy
