#@ load("@ytt:data", "data")
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
  - imageRepo: cloudfoundry/cloud-controller-ng
    path: #@ data.values.src_dirs.ccng
  - imageRepo: #@ data.values.kbld.destination.ccng
    path: #@ data.values.src_dirs.ccng
  - imageRepo: cloudfoundry/cf-api-controllers
    path: #@ data.values.src_dirs.cf_api_controllers
    pack: &packConfig
      build:
        builder: paketobuildpacks/builder:full
  - imageRepo: #@ data.values.kbld.destination.cf_api_controllers
    path: #@ data.values.src_dirs.cf_api_controllers
    pack: *packConfig
  - imageRepo: cloudfoundry/cf-api-package-image-uploader
    path: #@ data.values.src_dirs.package_image_uploader
    pack: *packConfig
  - imageRepo: #@ data.values.kbld.destination.package_image_uploader
    path: #@ data.values.src_dirs.package_image_uploader
    pack: *packConfig
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
  - imageRepo: cloudfoundry/cloud-controller-ng
    newImage: #@ data.values.kbld.destination.ccng
  - imageRepo: #@ data.values.kbld.destination.ccng
    newImage: #@ data.values.kbld.destination.ccng
  - imageRepo: cloudfoundry/cf-api-controllers
    newImage: #@ data.values.kbld.destination.cf_api_controllers
  - imageRepo: #@ data.values.kbld.destination.cf_api_controllers
    newImage: #@ data.values.kbld.destination.cf_api_controllers
  - imageRepo: cloudfoundry/cf-api-package-image-uploader
    newImage: #@ data.values.kbld.destination.package_image_uploader
  - imageRepo: #@ data.values.kbld.destination.package_image_uploader
    newImage: #@ data.values.kbld.destination.package_image_uploader
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageKeys
keys:
- ccng
- cf_api_controllers
- package_image_uploader
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.16.0
