// Code generated by counterfeiter. DO NOT EDIT.
package watcherfakes

import (
	"capi_kpack_watcher/capi_model"
	"capi_kpack_watcher/watcher"
	"sync"
)

type FakeBuildUpdater struct {
	UpdateBuildStub        func(string, capi_model.Build) error
	updateBuildMutex       sync.RWMutex
	updateBuildArgsForCall []struct {
		arg1 string
		arg2 capi_model.Build
	}
	updateBuildReturns struct {
		result1 error
	}
	updateBuildReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBuildUpdater) UpdateBuild(arg1 string, arg2 capi_model.Build) error {
	fake.updateBuildMutex.Lock()
	ret, specificReturn := fake.updateBuildReturnsOnCall[len(fake.updateBuildArgsForCall)]
	fake.updateBuildArgsForCall = append(fake.updateBuildArgsForCall, struct {
		arg1 string
		arg2 capi_model.Build
	}{arg1, arg2})
	fake.recordInvocation("UpdateBuild", []interface{}{arg1, arg2})
	fake.updateBuildMutex.Unlock()
	if fake.UpdateBuildStub != nil {
		return fake.UpdateBuildStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.updateBuildReturns
	return fakeReturns.result1
}

func (fake *FakeBuildUpdater) UpdateBuildCallCount() int {
	fake.updateBuildMutex.RLock()
	defer fake.updateBuildMutex.RUnlock()
	return len(fake.updateBuildArgsForCall)
}

func (fake *FakeBuildUpdater) UpdateBuildCalls(stub func(string, capi_model.Build) error) {
	fake.updateBuildMutex.Lock()
	defer fake.updateBuildMutex.Unlock()
	fake.UpdateBuildStub = stub
}

func (fake *FakeBuildUpdater) UpdateBuildArgsForCall(i int) (string, capi_model.Build) {
	fake.updateBuildMutex.RLock()
	defer fake.updateBuildMutex.RUnlock()
	argsForCall := fake.updateBuildArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBuildUpdater) UpdateBuildReturns(result1 error) {
	fake.updateBuildMutex.Lock()
	defer fake.updateBuildMutex.Unlock()
	fake.UpdateBuildStub = nil
	fake.updateBuildReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBuildUpdater) UpdateBuildReturnsOnCall(i int, result1 error) {
	fake.updateBuildMutex.Lock()
	defer fake.updateBuildMutex.Unlock()
	fake.UpdateBuildStub = nil
	if fake.updateBuildReturnsOnCall == nil {
		fake.updateBuildReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateBuildReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBuildUpdater) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.updateBuildMutex.RLock()
	defer fake.updateBuildMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBuildUpdater) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ watcher.BuildUpdater = new(FakeBuildUpdater)
