// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "capi_kpack_watcher/model"

	mock "github.com/stretchr/testify/mock"
)

// CAPI is an autogenerated mock type for the CAPI type
type CAPI struct {
	mock.Mock
}

// PATCHBuild provides a mock function with given fields: guid, status
func (_m *CAPI) PATCHBuild(guid string, status model.BuildStatus) error {
	ret := _m.Called(guid, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, model.BuildStatus) error); ok {
		r0 = rf(guid, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
