// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Kubernetes is an autogenerated mock type for the Kubernetes type
type Kubernetes struct {
	mock.Mock
}

// GetContainerLogs provides a mock function with given fields: podName, containerName
func (_m *Kubernetes) GetContainerLogs(podName string, containerName string) ([]byte, error) {
	ret := _m.Called(podName, containerName)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(podName, containerName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(podName, containerName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
